// Pure helpers for decision-log: parsing, serializing, numbering, search and the text the tool returns.
import type { Decision, DecisionEntry, DecisionStatus } from '../types'

export const STATUSES: readonly DecisionStatus[] = ['proposed', 'accepted', 'superseded', 'rejected']
export const INDEX_FILE = 'README.md'
export const INDEX_MARKER = '<!-- generated by the decision-log plugin; edits here are overwritten -->'

// ---------------------------------------------------------------------------------------------------------------
// Small text helpers

export function pad4(id: number): string {
  return String(id).padStart(4, '0')
}

/** One line, collapsed whitespace, at most `max` characters. */
export function oneLine(text: string, max = 200): string {
  const flat = text.replace(/\s+/g, ' ').trim()
  return flat.length <= max ? flat : `${flat.slice(0, max - 1).trimEnd()}…`
}

export function clip(text: string, max: number): string {
  return text.length <= max ? text : `${text.slice(0, Math.max(max - 1, 1))}…`
}

/** Lowercase ASCII words joined by `-`, at most 60 characters, `decision` when nothing is left. */
export function slugify(title: string): string {
  const ascii = title.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
  let slug = ascii.replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '')
  if (slug.length > 60) {
    const cut = slug.slice(0, 60)
    const lastDash = cut.lastIndexOf('-')
    slug = (lastDash >= 20 ? cut.slice(0, lastDash) : cut).replace(/-+$/g, '')
  }
  return slug === '' ? 'decision' : slug
}

export function fileName(id: number, title: string): string {
  return `${pad4(id)}-${slugify(title)}.md`
}

/** A file name inside the decisions folder that this plugin may read or write: no separators, no dot names. */
export function isSafeName(name: string): boolean {
  return name !== '' && name !== '.' && name !== '..' && !/[\\/\0]/.test(name) && !/^[A-Za-z]:/.test(name)
}

/** A decision file as named in a listing: `NNNN-anything.md`, the index excluded. */
export function isDecisionFile(name: string): boolean {
  return isSafeName(name) && /^\d+[-_ ].*\.md$/i.test(name) && name.toLowerCase() !== INDEX_FILE.toLowerCase()
}

export function idFromFileName(name: string): number | undefined {
  const match = /^(\d+)/.exec(name)
  if (match === null) return undefined
  const id = Number(match[1])
  return Number.isSafeInteger(id) && id > 0 ? id : undefined
}

export function isoDate(ms: number): string {
  return new Date(ms).toISOString().slice(0, 10)
}

/**
 * Validates the `dir` option: relative, `/`- or `\`-separated, no `.`/`..` segment. Answers the clean segments,
 * or an error.
 */
export function dirSegments(dir: string): { segments: string[] } | { error: string } {
  const trimmed = dir.trim()
  if (trimmed === '') return { error: 'the decisions folder option is empty' }
  if (/^([\\/]|[A-Za-z]:|~)/.test(trimmed)) return { error: `the decisions folder must be relative to the repository root, not "${trimmed}"` }
  const segments = trimmed.split(/[\\/]+/).filter(s => s !== '' && s !== '.')
  if (segments.length === 0) return { error: 'the decisions folder cannot be the repository root itself' }
  if (segments.some(s => s === '..' || /\0/.test(s))) return { error: `the decisions folder may not leave the repository ("${trimmed}")` }
  return { segments }
}

// ---------------------------------------------------------------------------------------------------------------
// Front matter (a tolerant subset of YAML: scalars, flow lists, block lists)

function unquote(raw: string): string {
  const value = raw.trim()
  if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
    return value.slice(1, -1).replace(/\\(["\\nt])/g, (_m, c: string) => (c === 'n' ? '\n' : c === 't' ? '\t' : c))
  }
  if (value.length >= 2 && value.startsWith("'") && value.endsWith("'")) return value.slice(1, -1).replace(/''/g, "'")
  // A trailing comment on a plain scalar.
  return value.replace(/\s+#.*$/, '')
}

/** Splits `[a, "b, c", d]` (brackets included or not) on commas outside quotes. */
function splitFlow(raw: string): string[] {
  let inner = raw.trim()
  if (inner.startsWith('[')) inner = inner.slice(1)
  if (inner.endsWith(']')) inner = inner.slice(0, -1)
  const parts: string[] = []
  let current = ''
  let quote: string | undefined
  for (let i = 0; i < inner.length; i++) {
    const ch = inner[i] as string
    if (quote !== undefined) {
      current += ch
      if (ch === '\\' && quote === '"' && i + 1 < inner.length) {
        current += inner[++i] as string
      } else if (ch === quote) quote = undefined
    } else if (ch === '"' || ch === "'") {
      quote = ch
      current += ch
    } else if (ch === ',') {
      parts.push(current)
      current = ''
    } else current += ch
  }
  parts.push(current)
  return parts.map(unquote).filter(p => p !== '')
}

type RawMeta = { key: string; scalar?: string; list?: string[]; raw: string }

function parseFrontMatter(lines: string[]): RawMeta[] {
  const out: RawMeta[] = []
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] as string
    if (line.trim() === '' || line.trimStart().startsWith('#')) continue
    const match = /^([A-Za-z_][\w -]*?)\s*:(.*)$/.exec(line)
    if (match === null) continue
    const key = (match[1] as string).trim()
    const rest = (match[2] as string).trim()
    if (rest === '' || rest === '|' || rest === '>') {
      // A block list (`- a`) or a block scalar on the indented lines below.
      const block: string[] = []
      while (i + 1 < lines.length && /^(\s+|-\s)/.test(lines[i + 1] as string) && !/^[A-Za-z_][\w -]*:/.test(lines[i + 1] as string)) {
        block.push(lines[++i] as string)
      }
      const items = block.filter(l => l.trim() !== '')
      if (items.length > 0 && items.every(l => /^\s*-\s/.test(l) || /^\s*-$/.test(l))) {
        out.push({ key, list: items.map(l => unquote(l.replace(/^\s*-\s?/, ''))).filter(v => v !== ''), raw: [rest, ...block].join('\n') })
      } else {
        out.push({ key, scalar: items.map(l => l.trim()).join(rest === '|' ? '\n' : ' '), raw: [rest, ...block].join('\n') })
      }
    } else if (rest.startsWith('[')) {
      out.push({ key, list: splitFlow(rest), raw: rest })
    } else {
      out.push({ key, scalar: unquote(rest), raw: rest })
    }
  }
  return out
}

function normKey(key: string): string {
  const k = key.trim().toLowerCase().replace(/[_ ]+/g, '-')
  if (k === 'supersededby' || k === 'superseded') return 'superseded-by'
  if (k === 'decider' || k === 'deciders') return 'deciders'
  if (k === 'tag' || k === 'tags') return 'tags'
  if (k === 'file' || k === 'files') return 'files'
  return k
}

function listOf(meta: RawMeta): string[] {
  if (meta.list !== undefined) return meta.list
  const scalar = meta.scalar ?? ''
  if (scalar === '' || scalar === '~' || scalar.toLowerCase() === 'null') return []
  return scalar.split(',').map(s => unquote(s)).filter(s => s !== '')
}

function idsOf(meta: RawMeta): number[] {
  const ids: number[] = []
  for (const item of listOf(meta)) {
    for (const match of item.matchAll(/\d+/g)) {
      const n = Number(match[0])
      if (Number.isSafeInteger(n) && n > 0 && !ids.includes(n)) ids.push(n)
    }
  }
  return ids
}

export function normStatus(raw: string | undefined): DecisionStatus | undefined {
  const s = (raw ?? '').trim().toLowerCase()
  if ((STATUSES as readonly string[]).includes(s)) return s as DecisionStatus
  if (s === 'deprecated' || s.startsWith('superseded')) return 'superseded'
  if (s === 'approved' || s === 'done' || s === 'adopted') return 'accepted'
  if (s === 'draft' || s === 'open' || s === 'pending') return 'proposed'
  if (s === 'declined' || s === 'abandoned') return 'rejected'
  return undefined
}

// ---------------------------------------------------------------------------------------------------------------
// Parse

const SECTION_ALIASES: Record<string, 'context' | 'decision' | 'alternatives' | 'consequences'> = {
  context: 'context',
  'context and problem statement': 'context',
  'problem statement': 'context',
  problem: 'context',
  background: 'context',
  decision: 'decision',
  'decision outcome': 'decision',
  outcome: 'decision',
  'alternatives considered': 'alternatives',
  alternatives: 'alternatives',
  'considered options': 'alternatives',
  'options considered': 'alternatives',
  options: 'alternatives',
  consequences: 'consequences',
  implications: 'consequences',
}

/** Trims blank lines at both ends and trailing spaces on each line. */
function tidy(text: string): string {
  return text
    .split('\n')
    .map(l => l.replace(/[ \t]+$/, ''))
    .join('\n')
    .replace(/^\n+|\n+$/g, '')
}

/** A markdown list into items (continuation lines indented); a non-list text is one item. */
export function parseAlternatives(body: string): string[] {
  const text = tidy(body)
  if (text === '') return []
  const lines = text.split('\n')
  const items: string[] = []
  let isList = true
  for (const line of lines) {
    const bullet = /^\s{0,3}(?:[-*+]|\d+[.)])\s+(.*)$/.exec(line)
    if (bullet !== null) items.push(bullet[1] as string)
    else if (line.trim() === '') {
      if (items.length > 0) items[items.length - 1] += '\n'
    }
    else if (/^\s+/.test(line) && items.length > 0) items[items.length - 1] += `\n${line.replace(/^\s{1,4}/, '')}`
    else {
      isList = false
      break
    }
  }
  if (!isList) return [text]
  return items.map(tidy).filter(i => i !== '')
}

function emptyDecision(): Decision {
  return {
    id: 0,
    title: '',
    status: 'proposed',
    date: '',
    deciders: [],
    supersedes: [],
    supersededBy: [],
    tags: [],
    files: [],
    context: '',
    decision: '',
    alternatives: [],
    consequences: '',
    preamble: '',
    extraSections: [],
    extraMeta: [],
  }
}

/**
 * Parses a decision file, tolerating hand edits: CRLF, a BOM, no front matter, block or flow lists, quoted values,
 * MADR-style section names, missing sections. `fileName` gives the id and the title when the file lacks them.
 */
export function parseDecision(source: string, fileName?: string): Decision {
  const d = emptyDecision()
  const text = source.replace(/^\uFEFF/, '').replace(/\r\n?/g, '\n')
  let lines = text.split('\n')

  if ((lines[0] ?? '').trim() === '---') {
    const end = lines.findIndex((l, i) => i > 0 && (l.trim() === '---' || l.trim() === '...'))
    if (end > 0) {
      for (const meta of parseFrontMatter(lines.slice(1, end))) {
        const key = normKey(meta.key)
        switch (key) {
          case 'id': {
            const n = Number(/\d+/.exec(meta.scalar ?? '')?.[0])
            if (Number.isSafeInteger(n) && n > 0) d.id = n
            break
          }
          case 'title':
            d.title = oneLine(meta.scalar ?? listOf(meta).join(', '))
            break
          case 'status':
            d.status = normStatus(meta.scalar) ?? 'proposed'
            break
          case 'date':
            d.date = (meta.scalar ?? '').trim()
            break
          case 'deciders':
            d.deciders = listOf(meta)
            break
          case 'supersedes':
            d.supersedes = idsOf(meta)
            break
          case 'superseded-by':
            d.supersededBy = idsOf(meta)
            break
          case 'tags':
            d.tags = listOf(meta)
            break
          case 'files':
            d.files = listOf(meta)
            break
          default:
            d.extraMeta.push([meta.key, meta.raw])
        }
      }
      lines = lines.slice(end + 1)
    }
  }

  let current: { key: string; heading: string; lines: string[] } | undefined
  const preamble: string[] = []
  const sections: { key: string; heading: string; lines: string[] }[] = []
  let fence: string | undefined
  let sawTitle = false
  for (const line of lines) {
    const fenceMatch = /^\s{0,3}(`{3,}|~{3,})/.exec(line)
    if (fenceMatch !== null) {
      const marker = (fenceMatch[1] as string)[0] as string
      if (fence === undefined) fence = marker
      else if (fence === marker) fence = undefined
    }
    if (fence === undefined || fenceMatch !== null) {
      const h1 = fence === undefined ? /^#\s+(.+?)\s*#*\s*$/.exec(line) : null
      if (h1 !== null && !sawTitle && current === undefined && preamble.every(l => l.trim() === '')) {
        sawTitle = true
        const heading = (h1[1] as string).trim()
        const numbered = /^(?:ADR[-\s]?)?(\d+)\s*[.:)\-–—]\s*(.+)$/i.exec(heading)
        if (numbered !== null) {
          if (d.id === 0) d.id = Number(numbered[1])
          if (d.title === '') d.title = oneLine(numbered[2] as string)
        } else if (d.title === '') d.title = oneLine(heading)
        continue
      }
      const h2 = fence === undefined ? /^##\s+(.+?)\s*#*\s*$/.exec(line) : null
      if (h2 !== null) {
        const heading = (h2[1] as string).trim()
        const key = SECTION_ALIASES[heading.toLowerCase().replace(/[:.]+$/, '')] ?? `extra:${heading}`
        current = { key, heading, lines: [] }
        sections.push(current)
        continue
      }
    }
    if (current === undefined) preamble.push(line)
    else current.lines.push(line)
  }

  d.preamble = tidy(preamble.join('\n'))
  for (const section of sections) {
    const body = tidy(section.lines.join('\n'))
    const join = (a: string) => (a === '' ? body : body === '' ? a : `${a}\n\n${body}`)
    switch (section.key) {
      case 'context':
        d.context = join(d.context)
        break
      case 'decision':
        d.decision = join(d.decision)
        break
      case 'consequences':
        d.consequences = join(d.consequences)
        break
      case 'alternatives':
        d.alternatives = [...d.alternatives, ...parseAlternatives(body)]
        break
      default:
        d.extraSections.push({ heading: section.heading, body })
    }
  }

  if (d.id === 0 && fileName !== undefined) d.id = idFromFileName(fileName) ?? 0
  if (d.title === '' && fileName !== undefined) {
    d.title = oneLine(fileName.replace(/\.md$/i, '').replace(/^\d+[-_ ]*/, '').replace(/[-_]+/g, ' ')) || `Decision ${d.id}`
  }
  return d
}

// ---------------------------------------------------------------------------------------------------------------
// Serialize

const RESERVED = /^(true|false|yes|no|on|off|null|~|-?\d[\d_.,]*|0x[0-9a-f]+)$/i

function quote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\t/g, '\\t')}"`
}

/** A scalar as plain YAML when that reads back the same, else double-quoted. */
export function yamlScalar(value: string): string {
  if (value === '') return '""'
  const isPlain = /^[A-Za-z0-9_./(@][^\n:#"'[\]{}]*$/.test(value) && !/\s$/.test(value) && !RESERVED.test(value) && !value.includes(': ')
  return isPlain ? value : quote(value)
}

function yamlItem(value: string): string {
  const isPlain = /^[A-Za-z0-9_./@+-][A-Za-z0-9_./@+ -]*$/.test(value) && !/\s$/.test(value) && !RESERVED.test(value) && !/^-\s/.test(value)
  return isPlain ? value : quote(value)
}

function yamlList(values: readonly (string | number)[]): string {
  return `[${values.map(v => (typeof v === 'number' ? String(v) : yamlItem(v))).join(', ')}]`
}

/** The markdown body (title heading and sections) without front matter: what a reader sees. */
export function serializeBody(d: Decision): string {
  const out: string[] = [`# ${d.id}. ${oneLine(d.title)}`, '']
  if (d.preamble !== '') out.push(d.preamble, '')
  const section = (heading: string, body: string) => {
    out.push(`## ${heading}`, '')
    if (body !== '') out.push(body, '')
  }
  section('Context', tidy(d.context))
  section('Decision', tidy(d.decision))
  section(
    'Alternatives considered',
    d.alternatives
      .map(tidy)
      .filter(a => a !== '')
      .map(a => `- ${a.split('\n').map(l => (l === '' ? '' : `  ${l}`)).join('\n').slice(2)}`)
      .join('\n'),
  )
  section('Consequences', tidy(d.consequences))
  for (const extra of d.extraSections) section(extra.heading, tidy(extra.body))
  while (out.length > 0 && out[out.length - 1] === '') out.pop()
  return `${out.join('\n')}\n`
}

/** Deterministic: fixed key order, flow lists, LF line endings, one trailing newline. */
export function serializeDecision(d: Decision): string {
  const meta = [
    '---',
    `id: ${d.id}`,
    `title: ${yamlScalar(oneLine(d.title))}`,
    `status: ${d.status}`,
    `date: ${yamlScalar(d.date)}`,
    `deciders: ${yamlList(d.deciders)}`,
    `supersedes: ${yamlList(d.supersedes)}`,
    `superseded-by: ${yamlList(d.supersededBy)}`,
    `tags: ${yamlList(d.tags)}`,
    `files: ${yamlList(d.files)}`,
    ...d.extraMeta.map(([k, raw]) => `${k}:${raw.startsWith('\n') || raw === '' ? '' : ' '}${raw}`),
    '---',
    '',
  ]
  return `${meta.join('\n')}${serializeBody(d)}`
}

// ---------------------------------------------------------------------------------------------------------------
// Numbering, index, listing, search

export function nextId(entries: readonly { id: number; file?: string }[], fileNames: readonly string[] = []): number {
  let max = 0
  for (const e of entries) max = Math.max(max, e.id)
  for (const name of fileNames) max = Math.max(max, idFromFileName(name) ?? 0)
  return max + 1
}

function cell(text: string): string {
  return oneLine(text, 120).replace(/\|/g, '\\|')
}

/** `<dir>/README.md`: a table of every record, oldest first. */
export function renderIndex(entries: readonly DecisionEntry[]): string {
  const rows = [...entries].sort((a, b) => a.id - b.id)
  const lines = [
    '# Decision log',
    '',
    INDEX_MARKER,
    '',
    'Architecture decision records for this repository. Record one with `/decide <title> — <why>` or ask Claude; browse with `/decisions`.',
    '',
    '| # | Title | Status | Date |',
    '| --- | --- | --- | --- |',
    ...rows.map(e => {
      const by = e.status === 'superseded' && e.supersededBy.length > 0 ? ` (by ${e.supersededBy.map(n => `#${n}`).join(', ')})` : ''
      return `| ${pad4(e.id)} | [${cell(e.title)}](${encodeURI(e.file)}) | ${e.status}${by} | ${cell(e.date)} |`
    }),
  ]
  if (rows.length === 0) lines.push('', '_No decisions recorded yet._')
  return `${lines.join('\n')}\n`
}

export function newestFirst<T extends { id: number }>(entries: readonly T[]): T[] {
  return [...entries].sort((a, b) => b.id - a.id)
}

export function supersededNote(d: Pick<Decision, 'supersededBy'>): string {
  return d.supersededBy.length === 0 ? '' : ` → ${d.supersededBy.map(n => `#${n}`).join(', ')}`
}

/** `#7 accepted 2026-10-06 Use SQLite [storage] → #9 (docs/decisions/0007-use-sqlite.md)` */
export function formatLine(e: DecisionEntry): string {
  const tags = e.tags.length > 0 ? ` [${e.tags.join(', ')}]` : ''
  return `#${e.id} ${e.status} ${e.date || '----------'} ${oneLine(e.title, 120)}${tags}${supersededNote(e)} (${e.path})`
}

export function filterEntries(entries: readonly DecisionEntry[], filter: { status?: string; tag?: string }): DecisionEntry[] {
  const status = filter.status === undefined ? undefined : normStatus(filter.status)
  const tag = filter.tag?.trim().toLowerCase()
  return newestFirst(entries).filter(
    e => (status === undefined || e.status === status) && (tag === undefined || tag === '' || e.tags.some(t => t.toLowerCase() === tag)),
  )
}

export function formatList(entries: readonly DecisionEntry[], dirPath: string, filter: { status?: string; tag?: string } = {}): string {
  const shown = filterEntries(entries, filter)
  const what = [filter.status, filter.tag === undefined ? undefined : `tag ${filter.tag}`].filter(Boolean).join(', ')
  if (shown.length === 0) {
    return entries.length === 0 ? `No decisions recorded yet in ${dirPath}/.` : `No decisions match (${what}). ${entries.length} in ${dirPath}/.`
  }
  const head = `${shown.length} decision${shown.length === 1 ? '' : 's'}${what === '' ? '' : ` (${what})`} in ${dirPath}/, newest first:`
  return [head, ...shown.map(formatLine)].join('\n')
}

export function plainBody(d: Decision): string {
  return [d.context, d.decision, ...d.alternatives, d.consequences, ...d.extraSections.map(s => s.body), d.preamble].join('\n')
}

export type SearchHit = { entry: DecisionEntry; score: number; snippet: string }

function snippetAround(text: string, terms: readonly string[], width = 140): string {
  const flat = text.replace(/\s+/g, ' ').trim()
  const lower = flat.toLowerCase()
  let at = -1
  for (const term of terms) {
    const i = lower.indexOf(term)
    if (i >= 0 && (at < 0 || i < at)) at = i
  }
  if (at < 0) return clip(flat, width)
  const start = Math.max(0, at - Math.floor(width / 3))
  const piece = flat.slice(start, start + width)
  return `${start > 0 ? '…' : ''}${piece}${start + width < flat.length ? '…' : ''}`
}

function countOf(haystack: string, needle: string): number {
  let n = 0
  let i = haystack.indexOf(needle)
  while (i >= 0 && n < 20) {
    n++
    i = haystack.indexOf(needle, i + needle.length)
  }
  return n
}

/** Ranks records by title (heaviest), tags, then body matches; the whole phrase scores extra. */
export function search(entries: readonly DecisionEntry[], query: string, limit = 10): SearchHit[] {
  const phrase = query.trim().toLowerCase()
  const terms = [...new Set(phrase.split(/[^\p{L}\p{N}_]+/u).filter(t => t.length > 0))]
  if (terms.length === 0) return []
  const hits: SearchHit[] = []
  for (const entry of entries) {
    const title = entry.title.toLowerCase()
    const tags = entry.tags.map(t => t.toLowerCase())
    const body = plainBody(entry).toLowerCase()
    let score = 0
    let matched = 0
    for (const term of terms) {
      const inTitle = countOf(title, term)
      const inTags = tags.filter(t => t === term).length * 2 + tags.filter(t => t.includes(term)).length
      const inBody = countOf(body, term)
      if (inTitle + inTags + inBody > 0) matched++
      score += inTitle * 6 + inTags * 4 + Math.min(inBody, 5)
    }
    if (matched === 0) continue
    score += matched === terms.length ? 5 : 0
    if (terms.length > 1 && (title.includes(phrase) || body.includes(phrase))) score += 8
    if (entry.status === 'superseded' || entry.status === 'rejected') score -= 1
    hits.push({ entry, score, snippet: snippetAround(plainBody(entry), terms) })
  }
  return hits.sort((a, b) => b.score - a.score || b.entry.id - a.entry.id).slice(0, limit)
}

export function formatSearch(hits: readonly SearchHit[], query: string): string {
  if (hits.length === 0) return `No decisions match "${query}".`
  return [
    `${hits.length} decision${hits.length === 1 ? '' : 's'} match "${query}", best first:`,
    ...hits.map(h => `${formatLine(h.entry)}\n    ${h.snippet}`),
  ].join('\n')
}

/** The full record for the model or a reader: the path, then the file as written. */
export function formatRecord(e: DecisionEntry): string {
  return `${e.path}\n\n${serializeDecision(e)}`
}

/** Markdown for the pane or the inline card: a meta line, then the body. */
export function recordMarkdown(e: DecisionEntry): string {
  const meta = [
    `**${e.status}**`,
    e.date,
    e.deciders.length > 0 ? `deciders: ${e.deciders.join(', ')}` : '',
    e.tags.length > 0 ? `tags: ${e.tags.join(', ')}` : '',
    e.supersedes.length > 0 ? `supersedes ${e.supersedes.map(n => `#${n}`).join(', ')}` : '',
    e.supersededBy.length > 0 ? `superseded by ${e.supersededBy.map(n => `#${n}`).join(', ')}` : '',
  ].filter(s => s !== '')
  const files = e.files.length > 0 ? `\n\nFiles: ${e.files.map(f => `\`${f}\``).join(', ')}` : ''
  const [heading, ...rest] = serializeBody(e).split('\n')
  return [heading, '', `${meta.join(' · ')}  \n\`${e.path}\`${files}`, ...rest].join('\n')
}

// ---------------------------------------------------------------------------------------------------------------
// Inputs

export type ToolRequest =
  | {
      action: 'record'
      title: string
      context: string
      decision: string
      alternatives: string[]
      consequences: string
      tags: string[]
      files: string[]
      deciders: string[]
      status: DecisionStatus
      supersedes: number[]
    }
  | { action: 'list'; status?: string; tag?: string }
  | { action: 'search'; query: string }
  | { action: 'get'; id: number }
  | { action: 'supersede'; id: number; by: number }
  | { action: 'set-status'; id: number; status: DecisionStatus }
  | { action: 'error'; message: string }

function str(v: unknown): string {
  return typeof v === 'string' ? v : typeof v === 'number' ? String(v) : ''
}

function strList(v: unknown): string[] {
  if (typeof v === 'string') return v.split(',').map(s => oneLine(s)).filter(s => s !== '')
  if (!Array.isArray(v)) return []
  return v.map(x => oneLine(str(x))).filter(s => s !== '')
}

function idOf(v: unknown): number | undefined {
  const n = typeof v === 'number' ? v : Number(/\d+/.exec(str(v))?.[0])
  return Number.isSafeInteger(n) && n > 0 ? n : undefined
}

export function parseToolInput(input: Record<string, unknown>): ToolRequest {
  const action = str(input.action)
  switch (action) {
    case 'record': {
      const title = oneLine(str(input.title))
      if (title === '') return { action: 'error', message: 'record needs a "title".' }
      const decision = str(input.decision).trim()
      if (decision === '') return { action: 'error', message: 'record needs "decision": what was decided.' }
      const statusRaw = input.status === undefined ? 'accepted' : str(input.status)
      const status = normStatus(statusRaw)
      if (status === undefined || status === 'superseded') {
        return { action: 'error', message: `record "status" must be proposed, accepted or rejected, not "${statusRaw}".` }
      }
      const supersedes = (Array.isArray(input.supersedes) ? input.supersedes : input.supersedes === undefined ? [] : [input.supersedes])
        .map(idOf)
        .filter((n): n is number => n !== undefined)
      const deciders = strList(input.deciders)
      return {
        action,
        title,
        context: str(input.context).trim(),
        decision,
        alternatives: Array.isArray(input.alternatives) ? input.alternatives.map(a => str(a).trim()).filter(a => a !== '') : strList(input.alternatives),
        consequences: str(input.consequences).trim(),
        tags: strList(input.tags).map(t => t.toLowerCase()),
        files: strList(input.files),
        deciders: deciders.length > 0 ? deciders : ['user', 'claude'],
        status,
        supersedes,
      }
    }
    case 'list': {
      const status = input.status === undefined ? undefined : str(input.status)
      if (status !== undefined && normStatus(status) === undefined) return { action: 'error', message: `Unknown status "${status}".` }
      return { action, status, tag: input.tag === undefined ? undefined : str(input.tag) }
    }
    case 'search': {
      const query = str(input.query).trim()
      return query === '' ? { action: 'error', message: 'search needs a "query".' } : { action, query }
    }
    case 'get': {
      const id = idOf(input.id)
      return id === undefined ? { action: 'error', message: 'get needs an "id" (the record number).' } : { action, id }
    }
    case 'supersede': {
      const id = idOf(input.id)
      const by = idOf(input.by)
      if (id === undefined || by === undefined) return { action: 'error', message: 'supersede needs "id" (the old record) and "by" (the new one).' }
      if (id === by) return { action: 'error', message: 'A record cannot supersede itself.' }
      return { action, id, by }
    }
    case 'set-status': {
      const id = idOf(input.id)
      const status = normStatus(str(input.status))
      if (id === undefined || status === undefined) {
        return { action: 'error', message: 'set-status needs "id" and "status" (proposed, accepted, superseded or rejected).' }
      }
      return { action, id, status }
    }
    default:
      return { action: 'error', message: `Unknown action "${action}". Use record, list, search, get, supersede or set-status.` }
  }
}

/** `/decide <title> — <why>`: the separators, in order of preference, are an em or en dash, `--`, then `:`. */
export function parseDecide(args: string): { title: string; why: string } | { error: string } {
  const text = args.trim()
  const usage = 'Usage: /decide <title> — <why>   (also `--` or `:` between them)'
  if (text === '') return { error: usage }
  for (const sep of [/\s*[—–]\s*/, /\s+--\s+|\s*--\s*/, /\s*:\s+|:\s*/]) {
    const match = sep.exec(text)
    if (match !== null && match.index > 0) {
      const title = oneLine(text.slice(0, match.index).replace(/^["']|["']$/g, ''))
      const why = text.slice(match.index + match[0].length).trim()
      if (title !== '') return { title, why }
    }
  }
  return { title: oneLine(text.replace(/^["']|["']$/g, '')), why: '' }
}

export type DecisionsCommand = { kind: 'list' } | { kind: 'show'; id: number } | { kind: 'search'; query: string } | { kind: 'error'; message: string }

export function parseDecisionsArgs(args: string): DecisionsCommand {
  const text = args.trim()
  if (text === '' || /^(list|ls|all)$/i.test(text)) return { kind: 'list' }
  const show = /^(?:show\s+|get\s+)?#?(\d+)$/i.exec(text)
  if (show !== null) return { kind: 'show', id: Number(show[1]) }
  const found = /^(?:search|find|grep)\s+(.+)$/i.exec(text)
  if (found !== null) return { kind: 'search', query: (found[1] as string).trim() }
  return { kind: 'error', message: 'Usage: /decisions | /decisions <n> | /decisions search <query>' }
}

/** The system-prompt section: where the log is and when to use it. */
export function guideText(dirPath: string, tool: string): string {
  return [
    `Decision log: this repository keeps architecture decision records in ${dirPath}/ (NNNN-slug.md), managed with the ${tool} tool.`,
    'When you and the user settle a genuine decision (architecture, a dependency, the data model, an API shape, a trade-off the user agreed to), record it with the why and the alternatives considered. Do not record trivial edits or routine fixes.',
    'Do not rewrite an accepted record: record the new decision and supersede the old one.',
    'When you need context on why something is the way it is, or before reversing an earlier choice, search the log and get the record.',
  ].join(' ')
}
